; DM2 — Práctica 2: Señales Físicas
; STM32F103C8T6 (Blue Pill) · PlatformIO + STM32Cube HAL

[env:bluepill_f103c8]
platform          = ststm32
board             = bluepill_f103c8
framework         = stm32cube
monitor_speed     = 115200
upload_protocol   = stlink

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    -Wall
    -Wextra

; Compilar solo src/ — la carpeta solucion/ es solo referencia
build_src_filter = +<*> -<../.pio>
